server:
  port: 8761
eureka:
  instance:
    hostname: eureka-8761
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8762/eureka,http://localhost:8763/eureka
spring:
  application:
    name: eureka-8761