server:
  port: 8762
eureka:
  instance:
    hostname: eureka-8762
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8763/eureka
spring:
  application:
    name: eureka-8762