server:
  port: 8763
eureka:
  instance:
    hostname: eureka-8763
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8763/eureka
spring:
  application:
    name: eureka-8763